{
  "type": "record",
  "name": "AvroRiskEvent",
  "namespace": "com.pnlengine.equities.streaming.avro",
  "fields": [
    {
      "name": "accountId",
      "type": "string"
    },
    {
      "name": "totalEquity",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 38,
        "scale": 18
      }
    },
    {
      "name": "marginRequirement",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 38,
        "scale": 18
      }
    },
    {
      "name": "breachAmount",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 38,
        "scale": 18
      }
    },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}
